import { AlertTriangle, CircleDollarSign, Plus, RefreshCw, RotateCcw, Search, ShieldCheck, WalletCards } from "lucide-react";
import { AccountantDepositCreateDialog } from "@/modules/payments/components/AccountantDepositCreateDialog";
import { AccountantDepositDeductionDialog } from "@/modules/payments/components/AccountantDepositDeductionDialog";
import { AccountantDepositDetailDrawer } from "@/modules/payments/components/AccountantDepositDetailDrawer";
import { AccountantDepositRefundDialog } from "@/modules/payments/components/AccountantDepositRefundDialog";
import { AccountantDepositTable } from "@/modules/payments/components/AccountantDepositTable";
import { AccountantPaymentPagination } from "@/modules/payments/components/AccountantPaymentPagination";
import { AccountantPaymentSummaryCard } from "@/modules/payments/components/AccountantPaymentSummaryCard";
import { formatPaymentCurrency } from "@/modules/payments/components/accountantPaymentFormatters";
import { useAccountantDeposits } from "@/modules/payments/hooks/useAccountantDeposits";
import type { AccountantDepositStatus } from "@/modules/payments/types/accountant-payment.types";

export const AccountantDepositsPage = () => {
  const vm = useAccountantDeposits(); const summary = vm.data.summary;
  return <div className="space-y-6">
    <section className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm font-semibold text-blue-600">Quản lý tài chính</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Tiền đặt cọc</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Theo dõi tiền cọc theo hóa đơn, số đang giữ và lịch sử hoàn cọc cho khách hàng.</p></div><div className="flex gap-3"><button type="button" onClick={() => vm.setCreateOpen(true)} className="inline-flex h-12 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white"><Plus size={17} /> Tạo tiền cọc</button><button type="button" disabled={vm.loading} onClick={() => void vm.load()} className="inline-flex h-12 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-600 shadow-sm hover:bg-blue-50 disabled:opacity-50"><RefreshCw size={17} className={vm.loading ? "animate-spin" : ""} /> Làm mới</button></div></section>
    {vm.error && <div className="flex items-start gap-3 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700"><AlertTriangle size={18} /> {vm.error}</div>}
    {vm.success && <button type="button" onClick={() => vm.setSuccess(null)} className="w-full rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-left text-sm font-medium text-emerald-700">{vm.success}<span className="float-right text-xs">Đóng</span></button>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><AccountantPaymentSummaryCard title="Tổng tiền cọc" value={formatPaymentCurrency(summary.totalDeposit)} description="Giá trị cọc trên hóa đơn" icon={CircleDollarSign} /><AccountantPaymentSummaryCard title="Đã thu cọc" value={formatPaymentCurrency(summary.heldAmount)} description="Tổng đã ghi nhận giữ cọc" icon={ShieldCheck} /><AccountantPaymentSummaryCard title="Sẵn sàng hoàn" value={formatPaymentCurrency(summary.refundableAmount)} description="Số cọc còn đang giữ" icon={WalletCards} /><AccountantPaymentSummaryCard title="Đã hoàn" value={formatPaymentCurrency(summary.refundedAmount)} description="Đã trả lại khách hàng" icon={RotateCcw} /></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid items-end gap-4 md:grid-cols-[minmax(260px,1fr)_220px_auto]"><label className="relative"><span className="sr-only">Tìm khoản cọc</span><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" /><input type="search" value={vm.search} onChange={(event) => vm.setSearch(event.target.value)} placeholder="Mã cọc, hóa đơn, khách hàng..." className="h-12 w-full rounded-xl border border-slate-200 pl-11 pr-4 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label><select value={vm.status} onChange={(event) => vm.setStatus(event.target.value as "ALL" | AccountantDepositStatus)} className="h-12 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700"><option value="ALL">Tất cả trạng thái</option><option value="PENDING">Chờ thu</option><option value="HELD">Đang giữ</option><option value="PARTIALLY_REFUNDED">Đã hoàn một phần</option><option value="REFUNDED">Đã hoàn</option></select><button type="button" onClick={vm.reset} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-semibold text-slate-600 hover:bg-blue-50"><RotateCcw size={17} /> Đặt lại</button></div></section>
    <div className="flex min-h-6 items-center justify-between gap-4"><p className="text-sm font-medium text-slate-500">Tìm thấy <span className="font-bold text-slate-800">{vm.filtered.length}</span> khoản cọc</p><ShieldCheck size={18} className="text-slate-300" /></div>
    <AccountantDepositTable deposits={vm.paginated} isLoading={vm.loading} onView={vm.setSelected} onRefund={(deposit) => { vm.setSelected(null); vm.setRefundTarget(deposit); }} />
    {!vm.loading && vm.filtered.length > 0 && <AccountantPaymentPagination currentPage={vm.page} totalPages={vm.totalPages} pageItems={vm.paginated.length} totalItems={vm.filtered.length} itemLabel="khoản cọc" onPageChange={vm.setPage} />}
    <AccountantDepositDetailDrawer deposit={vm.selected} onClose={() => vm.setSelected(null)} onDeduct={(deposit) => { vm.setSelected(null); vm.setDeductionTarget(deposit); }} onRefund={(deposit) => { vm.setSelected(null); vm.setRefundTarget(deposit); }} />
    <AccountantDepositDeductionDialog deposit={vm.deductionTarget} isSubmitting={vm.submitting} onClose={() => vm.setDeductionTarget(null)} onConfirm={(amount, reason) => void vm.deduct(amount, reason)} />
    <AccountantDepositRefundDialog deposit={vm.refundTarget} isSubmitting={vm.submitting} onClose={() => vm.setRefundTarget(null)} onConfirm={() => void vm.refund()} />
    <AccountantDepositCreateDialog open={vm.createOpen} organizationId={vm.organizationId} references={vm.references} isSubmitting={vm.submitting} onClose={() => vm.setCreateOpen(false)} onSubmit={vm.create} />
  </div>;
};
