import { CircleDollarSign, Landmark, MessageSquareText, X } from "lucide-react";
import { useEffect } from "react";
import type { AccountantPaymentMethod } from "@/modules/invoices";
import { AccountantReceivableBadge } from "@/modules/receivables/components/AccountantReceivableBadge";
import { formatReceivableCurrency, formatReceivableDate } from "@/modules/receivables/components/accountantReceivableFormatters";
import type { AccountantReceivable } from "@/modules/receivables/types/accountant-receivable.types";
const methods: Record<AccountantPaymentMethod, string> = { CASH: "Tiền mặt", BANK_TRANSFER: "Chuyển khoản", CARD: "Thẻ", OTHER: "Khác" };
interface Props { receivable: AccountantReceivable | null; isLoading: boolean; onClose: () => void; onPayment: (item: AccountantReceivable) => void; onNote: (item: AccountantReceivable) => void; }
export const AccountantReceivableDetailDrawer = ({ receivable, isLoading, onClose, onPayment, onNote }: Props) => {
  useEffect(() => { if (!receivable) return; const previous = document.body.style.overflow; const keydown = (e: KeyboardEvent) => e.key === "Escape" && onClose(); document.body.style.overflow = "hidden"; window.addEventListener("keydown", keydown); return () => { document.body.style.overflow = previous; window.removeEventListener("keydown", keydown); }; }, [onClose, receivable]);
  if (!receivable) return null;
  return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/30 backdrop-blur-[2px]"><button type="button" aria-label="Đóng" onClick={onClose} className="h-full flex-1" /><aside className="flex h-full w-full max-w-2xl flex-col bg-slate-50 shadow-2xl">
    <header className="flex items-start justify-between border-b border-slate-200 bg-white px-6 py-5"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Landmark size={22} /></span><div><p className="text-xs font-semibold uppercase text-blue-600">Chi tiết công nợ</p><h2 className="mt-1 text-xl font-bold text-slate-900">{receivable.receivableCode}</h2></div></div><button type="button" onClick={onClose} className="p-2 text-slate-400"><X size={20} /></button></header>
    <div className="flex-1 overflow-y-auto p-6">{isLoading ? <div className="space-y-4">{Array.from({ length: 5 }).map((_, i) => <div key={i} className="h-24 animate-pulse rounded-2xl bg-slate-200" />)}</div> : <div className="space-y-5">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-bold text-slate-900">Thông tin công nợ</h3><AccountantReceivableBadge status={receivable.status} /></div><dl className="mt-5 grid gap-4 sm:grid-cols-2">{[["Hóa đơn", receivable.invoiceCode], ["Đơn thuê", receivable.rentalCode], ["Hợp đồng", receivable.contractCode ?? "Chưa có"], ["Hạn thanh toán", formatReceivableDate(receivable.dueDate)], ["Chi nhánh", receivable.branchName]].map(([label, value]) => <div key={label}><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value}</dd></div>)}</dl></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-900">Khách hàng</h3><p className="mt-4 font-semibold text-slate-800">{receivable.customerName}</p><p className="mt-1 text-sm text-slate-500">{receivable.customerPhone} · {receivable.customerEmail}</p></section>
      <section className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-400">Tổng phải thu</p><p className="mt-2 font-bold text-slate-900">{formatReceivableCurrency(receivable.totalAmount)}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-400">Đã thu</p><p className="mt-2 font-bold text-emerald-700">{formatReceivableCurrency(receivable.paidAmount)}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-400">Còn lại</p><p className={`mt-2 font-bold ${receivable.status === "OVERDUE" ? "text-rose-600" : "text-blue-700"}`}>{formatReceivableCurrency(receivable.outstandingAmount)}</p></div></section>
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><h3 className="border-b border-slate-100 px-5 py-4 font-bold text-slate-900">Lịch sử thanh toán</h3>{receivable.payments.length === 0 ? <p className="px-5 py-8 text-center text-sm text-slate-400">Chưa có giao dịch.</p> : receivable.payments.map((payment) => <div key={payment.id} className="border-b border-slate-100 px-5 py-4 last:border-0"><div className="flex justify-between gap-3"><strong className={payment.status === "VOIDED" ? "text-slate-400 line-through" : "text-slate-800"}>{formatReceivableCurrency(payment.amount)}</strong><span className="text-xs text-slate-400">{formatReceivableDate(payment.paidAt)}</span></div><p className="mt-2 text-sm text-slate-500">{methods[payment.method]} · {payment.referenceCode ?? "Không có mã tham chiếu"}</p></div>)}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-bold text-slate-900">Ghi chú nghiệp vụ</h3><button type="button" onClick={() => onNote(receivable)} className="text-sm font-semibold text-blue-600">Chỉnh sửa</button></div><p className="mt-3 text-sm leading-6 text-slate-500">{receivable.note ?? "Chưa có ghi chú."}</p></section>
    </div>}</div>
    <footer className="grid grid-cols-2 gap-3 border-t border-slate-200 bg-white p-4"><button type="button" onClick={() => onNote(receivable)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 text-sm font-semibold text-slate-700"><MessageSquareText size={17} /> Ghi chú</button><button type="button" disabled={receivable.status === "PAID"} onClick={() => onPayment(receivable)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 text-sm font-semibold text-white disabled:bg-slate-300"><CircleDollarSign size={17} /> Ghi nhận thanh toán</button></footer>
  </aside></div>;
};
