import { CircleDollarSign, Eye } from "lucide-react";
import { AccountantReceivableBadge } from "@/modules/receivables/components/AccountantReceivableBadge";
import { formatReceivableCurrency, formatReceivableDate } from "@/modules/receivables/components/accountantReceivableFormatters";
import type { AccountantReceivable } from "@/modules/receivables/types/accountant-receivable.types";
interface Props { receivables: AccountantReceivable[]; isLoading: boolean; onView: (item: AccountantReceivable) => void; onPayment: (item: AccountantReceivable) => void; }
export const AccountantReceivableTable = ({ receivables, isLoading, onView, onPayment }: Props) => {
  if (isLoading) return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="space-y-3">{Array.from({ length: 5 }).map((_, i) => <div key={i} className="h-20 animate-pulse rounded-xl bg-slate-100" />)}</div></section>;
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1580px] border-collapse">
    <thead><tr className="border-b border-slate-200 bg-slate-50/80">{["Mã công nợ", "Khách hàng", "Đơn thuê", "Hóa đơn", "Tổng", "Đã thu", "Còn lại", "Hạn thanh toán", "Trạng thái", "Thao tác"].map((h) => <th key={h} className={`px-4 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500 ${["Tổng", "Đã thu", "Còn lại"].includes(h) ? "text-right" : "text-left"}`}>{h}</th>)}</tr></thead>
    <tbody>{receivables.length === 0 ? <tr><td colSpan={10} className="px-6 py-16 text-center"><p className="font-semibold text-slate-700">Không tìm thấy công nợ</p><p className="mt-2 text-sm text-slate-400">Hãy thay đổi bộ lọc hiện tại.</p></td></tr> : receivables.map((item) => <tr key={item.id} className="border-b border-slate-100 last:border-b-0 hover:bg-blue-50/30">
      <td className="whitespace-nowrap px-4 py-4 align-top"><button type="button" onClick={() => onView(item)} className="font-semibold text-blue-700">{item.receivableCode}</button><p className="mt-1 text-xs text-slate-400">{item.branchName}</p></td>
      <td className="px-4 py-4 align-top"><p className="max-w-64 truncate font-semibold text-slate-700">{item.customerName}</p><p className="mt-1 text-xs text-slate-400">{item.customerPhone}</p></td><td className="whitespace-nowrap px-4 py-4 align-top font-semibold text-slate-700">{item.rentalCode}</td><td className="whitespace-nowrap px-4 py-4 align-top font-semibold text-slate-700">{item.invoiceCode}</td>
      <td className="whitespace-nowrap px-4 py-4 text-right align-top font-semibold text-slate-700">{formatReceivableCurrency(item.totalAmount)}</td><td className="whitespace-nowrap px-4 py-4 text-right align-top font-semibold text-slate-700">{formatReceivableCurrency(item.paidAmount)}</td><td className={`whitespace-nowrap px-4 py-4 text-right align-top font-bold ${item.status === "OVERDUE" ? "text-rose-600" : "text-slate-900"}`}>{formatReceivableCurrency(item.outstandingAmount)}</td>
      <td className={`whitespace-nowrap px-4 py-4 align-top font-semibold ${item.status === "OVERDUE" ? "text-rose-600" : "text-slate-700"}`}>{formatReceivableDate(item.dueDate)}</td><td className="px-4 py-4 align-top"><AccountantReceivableBadge status={item.status} /></td>
      <td className="px-4 py-4 align-top"><div className="flex gap-1"><button type="button" title="Xem chi tiết" onClick={() => onView(item)} className="inline-flex size-9 items-center justify-center rounded-lg text-slate-500 hover:bg-blue-50 hover:text-blue-700"><Eye size={17} /></button><button type="button" title="Ghi nhận thanh toán" disabled={item.status === "PAID" || item.outstandingAmount <= 0} onClick={() => onPayment(item)} className="inline-flex size-9 items-center justify-center rounded-lg text-emerald-600 hover:bg-emerald-50 disabled:opacity-30"><CircleDollarSign size={17} /></button></div></td>
    </tr>)}</tbody>
  </table></div></section>;
};
