import { Eye } from "lucide-react";
import { formatReceivableCurrency } from "@/modules/receivables/components/accountantReceivableFormatters";
import type { AccountantDebtAgingRow } from "@/modules/receivables/types/accountant-receivable.types";
interface Props { rows: AccountantDebtAgingRow[]; isLoading: boolean; onViewReceivables: () => void; }
const labels = { GOOD: "Tốt", WARNING: "Cảnh báo", CRITICAL: "Nghiêm trọng" } as const;
const classes = { GOOD: "bg-emerald-50 text-emerald-700", WARNING: "bg-amber-50 text-amber-700", CRITICAL: "bg-rose-50 text-rose-700" } as const;
export const AccountantDebtAgingTable = ({ rows, isLoading, onViewReceivables }: Props) => {
  if (isLoading) return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="space-y-3">{Array.from({ length: 5 }).map((_, i) => <div key={i} className="h-16 animate-pulse rounded-xl bg-slate-100" />)}</div></section>;
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] border-collapse"><thead><tr className="border-b border-slate-200 bg-slate-50/80">{["Khách hàng", "Tổng công nợ", "Hiện tại", "1–30 ngày", ">30 ngày", "Số hóa đơn", "Trạng thái", "Thao tác"].map((h) => <th key={h} className={`px-4 py-4 text-xs font-semibold uppercase text-slate-500 ${["Tổng công nợ", "Hiện tại", "1–30 ngày", ">30 ngày", "Số hóa đơn"].includes(h) ? "text-right" : "text-left"}`}>{h}</th>)}</tr></thead><tbody>{rows.length === 0 ? <tr><td colSpan={8} className="px-6 py-16 text-center"><p className="font-semibold text-slate-700">Không có dữ liệu công nợ phù hợp</p></td></tr> : rows.map((row) => <tr key={row.customerId} className="border-b border-slate-100 last:border-0"><td className="px-4 py-4 font-semibold text-slate-700">{row.customerName}</td><td className="whitespace-nowrap px-4 py-4 text-right font-bold text-slate-900">{formatReceivableCurrency(row.totalDebt)}</td><td className="whitespace-nowrap px-4 py-4 text-right text-slate-600">{formatReceivableCurrency(row.currentAmount)}</td><td className="whitespace-nowrap px-4 py-4 text-right text-amber-700">{formatReceivableCurrency(row.oneToThirtyDays)}</td><td className="whitespace-nowrap px-4 py-4 text-right font-semibold text-rose-600">{formatReceivableCurrency(row.overThirtyDays)}</td><td className="px-4 py-4 text-right text-slate-600">{row.invoiceCount}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${classes[row.status]}`}>{labels[row.status]}</span></td><td className="px-4 py-4"><button type="button" onClick={onViewReceivables} className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600 hover:text-blue-700"><Eye size={16} /> Xem công nợ</button></td></tr>)}</tbody></table></div></section>;
};
