import { LoaderCircle, MessageSquareText, X } from "lucide-react";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import type { AccountantReceivable } from "@/modules/receivables/types/accountant-receivable.types";
interface Props { receivable: AccountantReceivable | null; isSubmitting: boolean; onClose: () => void; onSubmit: (note: string) => Promise<void>; }
export const AccountantReceivableNoteDialog = ({ receivable, isSubmitting, onClose, onSubmit }: Props) => {
  const [note, setNote] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (receivable) { setNote(receivable.note ?? ""); setError(""); } }, [receivable]); if (!receivable) return null;
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (note.trim().length > 300) { setError("Ghi chú tối đa 300 ký tự."); return; } await onSubmit(note); };
  return createPortal(<div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm"><form onSubmit={(e) => void submit(e)} className="w-full max-w-lg overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><MessageSquareText size={19} /></span><div><h2 className="font-bold text-slate-900">Ghi chú công nợ</h2><p className="mt-1 text-xs text-slate-400">{receivable.receivableCode}</p></div></div><button type="button" onClick={onClose} className="p-2 text-slate-400"><X size={18} /></button></header><div className="p-6"><textarea rows={6} value={note} onChange={(e) => { setNote(e.target.value); setError(""); }} className="w-full rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" placeholder="Nhập ghi chú xử lý công nợ..." />{error && <p className="mt-2 text-sm text-rose-600">{error}</p>}</div><footer className="flex justify-end gap-3 border-t border-slate-100 bg-slate-50 px-6 py-4"><button type="button" onClick={onClose} className="h-10 rounded-xl border border-slate-300 bg-white px-5 text-sm font-semibold">Hủy</button><button type="submit" disabled={isSubmitting} className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-semibold text-white">{isSubmitting && <LoaderCircle size={17} className="animate-spin" />} Lưu ghi chú</button></footer></form></div>, document.body);
};
