import { RotateCcw, Search } from "lucide-react";
import type { AccountantReconciliationStatus } from "@/modules/reconciliation/types/accountant-reconciliation.types";
export type ReconciliationStatusFilter = "ALL" | AccountantReconciliationStatus;
interface Props { branches: Array<{ id: string; name: string }>; search: string; branchId: string; status: ReconciliationStatusFilter; fromDate: string; toDate: string; disabled: boolean; onSearch: (v: string) => void; onBranch: (v: string) => void; onStatus: (v: ReconciliationStatusFilter) => void; onFromDate: (v: string) => void; onToDate: (v: string) => void; onReset: () => void; }
const control = "h-12 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-700 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100 disabled:bg-slate-100";
export const AccountantReconciliationFilters = (p: Props) => <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid items-end gap-4 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-[minmax(260px,1.5fr)_repeat(4,minmax(150px,0.8fr))_auto]">
  <label className="relative md:col-span-2 xl:col-span-1"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" /><input type="search" value={p.search} disabled={p.disabled} onChange={(e) => p.onSearch(e.target.value)} placeholder="Thanh toán, hóa đơn, khách hàng, tham chiếu..." className="h-12 w-full rounded-xl border border-slate-200 pl-11 pr-4 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>
  <select value={p.branchId} disabled={p.disabled} onChange={(e) => p.onBranch(e.target.value)} className={control}><option value="ALL">Tất cả chi nhánh</option>{p.branches.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select>
  <select value={p.status} disabled={p.disabled} onChange={(e) => p.onStatus(e.target.value as ReconciliationStatusFilter)} className={control}><option value="ALL">Tất cả trạng thái</option><option value="PENDING">Chờ đối soát</option><option value="MATCHED">Khớp</option><option value="MISMATCH">Lệch</option><option value="RECONCILED">Đã đối soát</option></select>
  <label className="grid gap-1 text-xs font-semibold text-slate-500">Từ ngày<input type="date" value={p.fromDate} onChange={(e) => p.onFromDate(e.target.value)} className={control} /></label><label className="grid gap-1 text-xs font-semibold text-slate-500">Đến ngày<input type="date" value={p.toDate} onChange={(e) => p.onToDate(e.target.value)} className={control} /></label>
  <button type="button" onClick={p.onReset} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-sm font-semibold text-slate-600 hover:bg-blue-50"><RotateCcw size={17} /> Đặt lại</button>
</div></section>;
