import { CheckCircle2, LoaderCircle, X } from "lucide-react";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { formatReconciliationCurrency } from "@/modules/reconciliation/components/accountantReconciliationFormatters";
import type { AccountantReconciliation, ConfirmReconciliationInput } from "@/modules/reconciliation/types/accountant-reconciliation.types";
interface Props { item: AccountantReconciliation | null; reconciledBy: string; isSubmitting: boolean; onClose: () => void; onSubmit: (input: ConfirmReconciliationInput) => Promise<void>; }
export const AccountantReconciliationConfirmDialog = ({ item, reconciledBy, isSubmitting, onClose, onSubmit }: Props) => {
  const [note, setNote] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (item) { setNote(""); setError(""); } }, [item]); if (!item) return null;
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (item.status === "MISMATCH" && note.trim().length < 5) { setError("Giao dịch lệch cần ghi cách xử lý tối thiểu 5 ký tự."); return; } await onSubmit({ reconciliationId: item.id, note, reconciledBy }); };
  return createPortal(<div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm"><form onSubmit={(e) => void submit(e)} className="w-full max-w-lg overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b border-slate-100 px-6 py-5"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><CheckCircle2 size={22} /></span><div><h2 className="font-bold text-slate-900">Xác nhận đối soát</h2><p className="mt-1 text-xs text-slate-400">{item.paymentId}</p></div></div><button type="button" onClick={onClose} className="p-2 text-slate-400"><X size={18} /></button></header><div className="space-y-4 p-6"><div className={`rounded-2xl border p-4 ${item.status === "MISMATCH" ? "border-rose-200 bg-rose-50" : "border-emerald-200 bg-emerald-50"}`}><p className="text-sm text-slate-600">Chênh lệch</p><p className={`mt-2 text-xl font-bold ${item.status === "MISMATCH" ? "text-rose-600" : "text-emerald-700"}`}>{formatReconciliationCurrency(item.differenceAmount)}</p></div><label className="block text-sm font-semibold text-slate-700">Ghi chú {item.status === "MISMATCH" && <span className="text-rose-500">*</span>}<textarea rows={4} value={note} onChange={(e) => { setNote(e.target.value); setError(""); }} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" placeholder={item.status === "MISMATCH" ? "Mô tả nguyên nhân và cách xử lý chênh lệch..." : "Ghi chú xác nhận (không bắt buộc)"} /></label>{error && <p className="text-sm text-rose-600">{error}</p>}</div><footer className="flex justify-end gap-3 border-t border-slate-100 bg-slate-50 px-6 py-4"><button type="button" onClick={onClose} className="h-10 rounded-xl border border-slate-300 bg-white px-5 text-sm font-semibold">Quay lại</button><button type="submit" disabled={isSubmitting} className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-5 text-sm font-semibold text-white">{isSubmitting && <LoaderCircle size={17} className="animate-spin" />} Xác nhận</button></footer></form></div>, document.body);
};
