import { CheckCircle2, Eye } from "lucide-react";
import { AccountantReconciliationBadge } from "@/modules/reconciliation/components/AccountantReconciliationBadge";
import { formatReconciliationCurrency, formatReconciliationDate } from "@/modules/reconciliation/components/accountantReconciliationFormatters";
import type { AccountantReconciliation } from "@/modules/reconciliation/types/accountant-reconciliation.types";
interface Props { items: AccountantReconciliation[]; isLoading: boolean; onView: (item: AccountantReconciliation) => void; onConfirm: (item: AccountantReconciliation) => void; }
export const AccountantReconciliationTable = ({ items, isLoading, onView, onConfirm }: Props) => {
  if (isLoading) return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="space-y-3">{Array.from({ length: 5 }).map((_, i) => <div key={i} className="h-20 animate-pulse rounded-xl bg-slate-100" />)}</div></section>;
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1500px] border-collapse"><thead><tr className="border-b border-slate-200 bg-slate-50/80">{["Thanh toán", "Hóa đơn", "Khách hàng", "Ngày giao dịch", "Mã tham chiếu", "Số kỳ vọng", "Số sao kê", "Chênh lệch", "Trạng thái", "Thao tác"].map((h) => <th key={h} className={`px-4 py-4 text-xs font-semibold uppercase text-slate-500 ${["Số kỳ vọng", "Số sao kê", "Chênh lệch"].includes(h) ? "text-right" : "text-left"}`}>{h}</th>)}</tr></thead><tbody>
    {items.length === 0 ? <tr><td colSpan={10} className="px-6 py-16 text-center"><p className="font-semibold text-slate-700">Không tìm thấy giao dịch đối soát</p><p className="mt-2 text-sm text-slate-400">Hãy thay đổi bộ lọc hiện tại.</p></td></tr> : items.map((item) => <tr key={item.id} className="border-b border-slate-100 last:border-0 hover:bg-blue-50/30"><td className="whitespace-nowrap px-4 py-4"><button type="button" onClick={() => onView(item)} className="font-semibold text-blue-700">{item.paymentId}</button><p className="mt-1 text-xs text-slate-400">{item.branchName}</p></td><td className="whitespace-nowrap px-4 py-4 font-semibold text-slate-700">{item.invoiceCode}</td><td className="px-4 py-4 font-semibold text-slate-700">{item.customerName}</td><td className="whitespace-nowrap px-4 py-4 text-sm text-slate-600">{formatReconciliationDate(item.transactionDate)}</td><td className="whitespace-nowrap px-4 py-4 text-sm text-slate-600">{item.referenceCode ?? "—"}</td><td className="whitespace-nowrap px-4 py-4 text-right font-semibold text-slate-700">{formatReconciliationCurrency(item.expectedAmount)}</td><td className="whitespace-nowrap px-4 py-4 text-right font-semibold text-slate-700">{formatReconciliationCurrency(item.statementAmount)}</td><td className={`whitespace-nowrap px-4 py-4 text-right font-bold ${item.differenceAmount === 0 ? "text-emerald-700" : "text-rose-600"}`}>{formatReconciliationCurrency(item.differenceAmount)}</td><td className="px-4 py-4"><AccountantReconciliationBadge status={item.status} /></td><td className="px-4 py-4"><div className="flex gap-1"><button type="button" onClick={() => onView(item)} title="Xem chi tiết" className="inline-flex size-9 items-center justify-center rounded-lg text-slate-500 hover:bg-blue-50 hover:text-blue-700"><Eye size={17} /></button><button type="button" disabled={!['MATCHED', 'MISMATCH'].includes(item.status)} onClick={() => onConfirm(item)} title="Xác nhận đối soát" className="inline-flex size-9 items-center justify-center rounded-lg text-emerald-600 hover:bg-emerald-50 disabled:opacity-30"><CheckCircle2 size={17} /></button></div></td></tr>)}
  </tbody></table></div></section>;
};
