import { CheckCircle2, Scale, X } from "lucide-react";
import { useEffect } from "react";
import { AccountantReconciliationBadge } from "@/modules/reconciliation/components/AccountantReconciliationBadge";
import { formatReconciliationCurrency, formatReconciliationDate, reconciliationMethodLabel } from "@/modules/reconciliation/components/accountantReconciliationFormatters";
import type { AccountantReconciliation } from "@/modules/reconciliation/types/accountant-reconciliation.types";
interface Props { item: AccountantReconciliation | null; isLoading: boolean; onClose: () => void; onConfirm: (item: AccountantReconciliation) => void; }
export const AccountantReconciliationDetailDrawer = ({ item, isLoading, onClose, onConfirm }: Props) => {
  useEffect(() => { if (!item) return; const previous = document.body.style.overflow; const keydown = (e: KeyboardEvent) => e.key === "Escape" && onClose(); document.body.style.overflow = "hidden"; window.addEventListener("keydown", keydown); return () => { document.body.style.overflow = previous; window.removeEventListener("keydown", keydown); }; }, [item, onClose]); if (!item) return null;
  const canConfirm = item.status === "MATCHED" || item.status === "MISMATCH";
  return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/30 backdrop-blur-[2px]"><button type="button" aria-label="Đóng" onClick={onClose} className="h-full flex-1" /><aside className="flex h-full w-full max-w-xl flex-col bg-slate-50 shadow-2xl"><header className="flex items-start justify-between border-b border-slate-200 bg-white px-6 py-5"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Scale size={22} /></span><div><p className="text-xs font-semibold uppercase text-blue-600">Chi tiết đối soát</p><h2 className="mt-1 font-bold text-slate-900">{item.paymentId}</h2></div></div><button type="button" onClick={onClose} className="p-2 text-slate-400"><X size={20} /></button></header>
    <div className="flex-1 overflow-y-auto p-6">{isLoading ? <div className="space-y-4">{Array.from({ length: 4 }).map((_, i) => <div key={i} className="h-24 animate-pulse rounded-2xl bg-slate-200" />)}</div> : <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-bold text-slate-900">Kết quả so sánh</h3><AccountantReconciliationBadge status={item.status} /></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">Theo thanh toán</p><p className="mt-2 font-bold text-slate-800">{formatReconciliationCurrency(item.expectedAmount)}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-400">Theo sao kê</p><p className="mt-2 font-bold text-slate-800">{formatReconciliationCurrency(item.statementAmount)}</p></div><div className={item.differenceAmount === 0 ? "rounded-xl bg-emerald-50 p-3" : "rounded-xl bg-rose-50 p-3"}><p className="text-xs text-slate-400">Chênh lệch</p><p className={`mt-2 font-bold ${item.differenceAmount === 0 ? "text-emerald-700" : "text-rose-600"}`}>{formatReconciliationCurrency(item.differenceAmount)}</p></div></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-900">Thông tin tham chiếu</h3><dl className="mt-4 grid gap-4 sm:grid-cols-2">{[["Hóa đơn", item.invoiceCode], ["Khách hàng", item.customerName], ["Mã tham chiếu", item.referenceCode ?? "Chưa có"], ["Ngày giao dịch", formatReconciliationDate(item.transactionDate)], ["Phương thức", reconciliationMethodLabel(item.paymentMethod)], ["Chi nhánh", item.branchName]].map(([label, value]) => <div key={label}><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-700">{value}</dd></div>)}</dl></section>
      {item.status === "PENDING" && <section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Đang chờ reference hoặc xác nhận giao dịch từ ngân hàng.</section>}{item.resolutionNote && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-900">Kết quả xử lý</h3><p className="mt-3 text-sm text-slate-600">{item.resolutionNote}</p><p className="mt-2 text-xs text-slate-400">{item.reconciledBy} · {item.reconciledAt ? formatReconciliationDate(item.reconciledAt) : ""}</p></section>}
    </div>}</div><footer className="border-t border-slate-200 bg-white p-4"><button type="button" disabled={!canConfirm} onClick={() => onConfirm(item)} className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 text-sm font-semibold text-white disabled:bg-slate-300"><CheckCircle2 size={18} /> Xác nhận đối soát</button></footer></aside></div>;
};
