import { AlertTriangle, CheckCircle2, CircleDotDashed, RefreshCw, Scale, TriangleAlert } from "lucide-react";
import { useAuthStore } from "@/modules/auth";
import { AccountantReconciliationConfirmDialog } from "@/modules/reconciliation/components/AccountantReconciliationConfirmDialog";
import { AccountantReconciliationDetailDrawer } from "@/modules/reconciliation/components/AccountantReconciliationDetailDrawer";
import { AccountantReconciliationFilters } from "@/modules/reconciliation/components/AccountantReconciliationFilters";
import { AccountantReconciliationPagination } from "@/modules/reconciliation/components/AccountantReconciliationPagination";
import { AccountantReconciliationSummaryCard } from "@/modules/reconciliation/components/AccountantReconciliationSummaryCard";
import { AccountantReconciliationTable } from "@/modules/reconciliation/components/AccountantReconciliationTable";
import { formatReconciliationCurrency } from "@/modules/reconciliation/components/accountantReconciliationFormatters";
import { useAccountantReconciliation } from "@/modules/reconciliation/hooks/useAccountantReconciliation";
import type { AccountantReconciliation } from "@/modules/reconciliation/types/accountant-reconciliation.types";
export const AccountantReconciliationPage = () => {
  const vm = useAccountantReconciliation(); const user = useAuthStore((s) => s.user); const summary = vm.data.summary;
  const openConfirm = (item: AccountantReconciliation) => { vm.setSelected(null); vm.setConfirmTarget(item); };
  return <div className="space-y-6"><section className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm font-semibold text-blue-600">Kiểm soát giao dịch</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">Đối soát thanh toán</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">So sánh thanh toán với sao kê theo số tiền, tham chiếu và ngày giao dịch trước khi xác nhận.</p></div><button type="button" disabled={vm.loading} onClick={() => void vm.load()} className="inline-flex h-12 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-600 shadow-sm hover:bg-blue-50 disabled:opacity-50"><RefreshCw size={17} className={vm.loading ? "animate-spin" : ""} /> Làm mới</button></section>
    <div className="flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800"><AlertTriangle size={18} className="shrink-0" /><span>MOCK / BACKEND NOT AVAILABLE — dữ liệu và thao tác đối soát trên màn hình này chưa được lưu vào backend.</span></div>
    {vm.error && <div className="flex gap-3 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700"><AlertTriangle size={18} /> {vm.error}</div>}{vm.success && <button type="button" onClick={() => vm.setSuccess(null)} className="w-full rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-left text-sm font-medium text-emerald-700">{vm.success}<span className="float-right text-xs">Đóng</span></button>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-5"><AccountantReconciliationSummaryCard title="Chờ dữ liệu" value={String(summary.pendingCount)} description="Chưa đủ tham chiếu/xác nhận" icon={CircleDotDashed} /><AccountantReconciliationSummaryCard title="Khớp" value={String(summary.matchedCount)} description="Sẵn sàng xác nhận" icon={CheckCircle2} /><AccountantReconciliationSummaryCard title="Lệch" value={String(summary.mismatchCount)} description="Cần xem xét thủ công" icon={TriangleAlert} tone="danger" /><AccountantReconciliationSummaryCard title="Đã đối soát" value={String(summary.reconciledCount)} description="Đã được kế toán xác nhận" icon={Scale} /><AccountantReconciliationSummaryCard title="Tổng chênh lệch" value={formatReconciliationCurrency(summary.differenceAmount)} description="Giá trị tuyệt đối cần xử lý" icon={TriangleAlert} tone={summary.differenceAmount > 0 ? "danger" : "default"} /></section>
    <AccountantReconciliationFilters branches={vm.branches} search={vm.search} branchId={vm.branchId} status={vm.status} fromDate={vm.fromDate} toDate={vm.toDate} disabled={vm.loading} onSearch={vm.setSearch} onBranch={vm.setBranchId} onStatus={vm.setStatus} onFromDate={vm.setFromDate} onToDate={vm.setToDate} onReset={vm.reset} />
    <div className="flex min-h-6 items-center justify-between gap-4"><p className="text-sm font-medium text-slate-500">Tìm thấy <strong className="text-slate-800">{vm.filtered.length}</strong> giao dịch</p><Scale size={18} className="text-slate-300" /></div><AccountantReconciliationTable items={vm.paginated} isLoading={vm.loading} onView={(item) => void vm.view(item)} onConfirm={openConfirm} />{!vm.loading && vm.filtered.length > 0 && <AccountantReconciliationPagination page={vm.page} totalPages={vm.totalPages} pageItems={vm.paginated.length} totalItems={vm.filtered.length} onChange={vm.setPage} />}
    <AccountantReconciliationDetailDrawer item={vm.selected} isLoading={vm.detailLoading} onClose={() => vm.setSelected(null)} onConfirm={openConfirm} /><AccountantReconciliationConfirmDialog item={vm.confirmTarget} reconciledBy={user?.fullName ?? "Kế toán"} isSubmitting={vm.submitting} onClose={() => vm.setConfirmTarget(null)} onSubmit={vm.confirm} />
  </div>;
};
