import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { LoaderCircle, X } from "lucide-react";
import type { InvoiceReferences } from "@/modules/invoices/api/accountant-invoice-reference.api";

export interface CreateDepositInput {
  organizationId: number; branchId: number; customerId: number; rentalOrderId: number;
  rentalContractId: number; amount: number; paymentMethod: "CASH" | "BANK_TRANSFER" | "QR";
  reference: string; notes: string;
}
interface Props { open: boolean; organizationId?: number; references: InvoiceReferences | null; isSubmitting: boolean; onClose: () => void; onSubmit: (input: CreateDepositInput) => Promise<void>; }

export const AccountantDepositCreateDialog = ({ open, organizationId, references, isSubmitting, onClose, onSubmit }: Props) => {
  const [orderId, setOrderId] = useState(""); const [contractId, setContractId] = useState(""); const [amount, setAmount] = useState(""); const [method, setMethod] = useState<CreateDepositInput["paymentMethod"]>("BANK_TRANSFER"); const [reference, setReference] = useState(""); const [error, setError] = useState("");
  useEffect(() => { if (open) { setOrderId(""); setContractId(""); setAmount(""); setReference(""); setError(""); } }, [open]);
  const order = references?.orders.find(({ id }) => String(id) === orderId); const contracts = useMemo(() => references?.contracts.filter((item) => !orderId || String(item.rentalOrderId) === orderId) ?? [], [orderId, references]); const contract = contracts.find(({ id }) => String(id) === contractId);
  if (!open) return null;
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const value = Number(amount); if (!organizationId || !order || !contract || !Number.isFinite(value) || value <= 0) { setError("Chọn đơn thuê, hợp đồng và nhập số tiền cọc hợp lệ."); return; } await onSubmit({ organizationId, branchId: order.branchId, customerId: order.customerId, rentalOrderId: order.id, rentalContractId: contract.id, amount: value, paymentMethod: method, reference, notes: "Accountant deposit" }); };
  return createPortal(<div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/50 p-4"><form onSubmit={(event) => void submit(event)} className="w-full max-w-xl overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b px-6 py-5"><h2 className="font-bold text-slate-900">Tạo khoản tiền cọc</h2><button type="button" onClick={onClose}><X size={19} /></button></header><div className="grid gap-4 p-6"><label className="text-sm font-semibold">Đơn thuê<select value={orderId} onChange={(event) => { setOrderId(event.target.value); setContractId(""); }} className="mt-2 h-11 w-full rounded-xl border px-3"><option value="">Chọn đơn thuê</option>{references?.orders.map((item) => <option key={item.id} value={item.id}>{item.orderCode}</option>)}</select></label><label className="text-sm font-semibold">Hợp đồng<select value={contractId} onChange={(event) => setContractId(event.target.value)} className="mt-2 h-11 w-full rounded-xl border px-3"><option value="">Chọn hợp đồng</option>{contracts.map((item) => <option key={item.id} value={item.id}>{item.contractCode}</option>)}</select></label><label className="text-sm font-semibold">Số tiền<input type="number" min="1" value={amount} onChange={(event) => setAmount(event.target.value)} className="mt-2 h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-semibold">Phương thức<select value={method} onChange={(event) => setMethod(event.target.value as CreateDepositInput["paymentMethod"])} className="mt-2 h-11 w-full rounded-xl border px-3"><option value="BANK_TRANSFER">Chuyển khoản</option><option value="CASH">Tiền mặt</option><option value="QR">QR</option></select></label><label className="text-sm font-semibold">Mã tham chiếu<input value={reference} onChange={(event) => setReference(event.target.value)} className="mt-2 h-11 w-full rounded-xl border px-3" /></label>{error && <p className="text-sm text-rose-600">{error}</p>}</div><footer className="flex justify-end gap-3 border-t bg-slate-50 px-6 py-4"><button type="button" onClick={onClose} className="h-10 rounded-xl border px-5">Hủy</button><button type="submit" disabled={isSubmitting} className="inline-flex h-10 items-center gap-2 rounded-xl bg-blue-600 px-5 font-semibold text-white">{isSubmitting && <LoaderCircle size={17} className="animate-spin" />} Tạo tiền cọc</button></footer></form></div>, document.body);
};
