import { AlertTriangle, CalendarClock, CircleDollarSign, Download, Search, TriangleAlert } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router";
import { accountantReceivablesApi } from "@/modules/receivables/api/accountant-receivables.api";
import { AccountantDebtAgingTable } from "@/modules/receivables/components/AccountantDebtAgingTable";
import { AccountantReceivablePagination } from "@/modules/receivables/components/AccountantReceivablePagination";
import { AccountantReceivableSummaryCard } from "@/modules/receivables/components/AccountantReceivableSummaryCard";
import { formatReceivableCurrency } from "@/modules/receivables/components/accountantReceivableFormatters";
import type { AccountantDebtAgingData } from "@/modules/receivables/types/accountant-receivable.types";
const PAGE_SIZE = 5; const empty: AccountantDebtAgingData = { rows: [], totalDebt: 0, currentAmount: 0, oneToThirtyDays: 0, overThirtyDays: 0 };
export const AccountantRevenueReportsPage = () => {
  const navigate = useNavigate(); const [data, setData] = useState(empty); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { let active = true; setLoading(true); accountantReceivablesApi.getDebtAging().then((result) => active && setData(result)).catch((caught: unknown) => active && setError(caught instanceof Error ? caught.message : "Không thể tải báo cáo công nợ.")).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return data.rows.filter((row) => !term || row.customerName.toLowerCase().includes(term)); }, [data.rows, search]);
  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const rows = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  useEffect(() => setPage(1), [search]); useEffect(() => { if (page > totalPages) setPage(totalPages); }, [page, totalPages]);
  const exportCsv = () => { const content = [["Khách hàng", "Tổng công nợ", "Hiện tại", "1-30 ngày", ">30 ngày"], ...filtered.map((r) => [r.customerName, r.totalDebt, r.currentAmount, r.oneToThirtyDays, r.overThirtyDays])].map((row) => row.map((cell) => `"${cell}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([`\ufeff${content}`], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "bao-cao-tuoi-no.csv"; a.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-6"><section className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm font-semibold text-blue-600">Báo cáo tài chính</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Báo cáo doanh thu & công nợ</h1><p className="mt-2 text-sm text-slate-500">Góc nhìn hẹp dành cho kế toán: số dư phải thu và tuổi nợ theo khách hàng.</p></div><button type="button" disabled={loading || filtered.length === 0} onClick={exportCsv} className="inline-flex h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-600 hover:bg-blue-50 disabled:opacity-50"><Download size={17} /> Xuất báo cáo</button></section>
    {error && <div className="flex gap-3 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"><AlertTriangle size={18} /> {error}</div>}
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><AccountantReceivableSummaryCard title="Tổng công nợ" value={formatReceivableCurrency(data.totalDebt)} description="Tổng còn phải thu" icon={CircleDollarSign} /><AccountantReceivableSummaryCard title="Hiện tại" value={formatReceivableCurrency(data.currentAmount)} description="Chưa đến hạn" icon={CalendarClock} /><AccountantReceivableSummaryCard title="1–30 ngày" value={formatReceivableCurrency(data.oneToThirtyDays)} description="Nợ quá hạn gần" icon={TriangleAlert} /><AccountantReceivableSummaryCard title=">30 ngày" value={formatReceivableCurrency(data.overThirtyDays)} description="Nợ cần xử lý khẩn" icon={TriangleAlert} tone="danger" /></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="relative block max-w-xl"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" /><input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm khách hàng..." className="h-11 w-full rounded-xl border border-slate-200 pl-11 pr-4 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label></section>
    <p className="text-sm font-medium text-slate-500">Tìm thấy <strong className="text-slate-800">{filtered.length}</strong> khách hàng có công nợ</p><AccountantDebtAgingTable rows={rows} isLoading={loading} onViewReceivables={() => navigate("/accounting/receivables")} />{!loading && filtered.length > 0 && <AccountantReceivablePagination page={page} totalPages={totalPages} pageItems={rows.length} totalItems={filtered.length} itemLabel="khách hàng" onChange={setPage} />}
  </div>;
};
